### ISSUE TITLE
Update to Symphony3?

### ISSUE THREAD

**Issue by Quix0r** [evispa/NercuryCodeIgniterBundle#8]
How much would it be to update this project to support latest stable Symphony3 ? Here at work we have CI2 (!) for some applications and I really want to migrate away from it (as you may know, it is a PHP4 framework which is not really up-to-date).

It would be helpful to migrate from CI2 to S3 directly so no need to double-port (CI2->S2->S3).

And thank you anyway for your work. 👍

**Comment by Nercury** [comment]
I don't have time to do this (I have changed two jobs since I wrote this),
but it should not be hard to do necessary changes (if any) yourself.

This bundle is quite simple: it injects custom request handler that checks
if request path matches any CI controller, and if so, loads up CI to handle
such request.

The code of custom request handler is straightforward:
https://github.com/evispa/NercuryCodeIgniterBundle/blob/master/DefaultCiActionResolver.php.
This is where I suggest you to start if you are going to reimplement
something similar.

The way it loads CI is hacked in ci_bootstrap. Most of that code is copy
pasted from real CI.

The most complicated part was making sure the relative paths are correct,
making it configurable and making it possible to access CI from symfony and
vice-versa.

**Comment by Nercury** [comment]
Whoops, I meant to use file https://github.com/evispa/NercuryCodeIgniterBundle/blob/master/CiRequestListenerService.php as starting point. This is the request handler I was talking about.

**Comment by pedroresende** [comment]
@Quix0r Were you able to do anything ?

**Comment by Quix0r** [comment]
Sorry, low time available.

**Comment by Nercury** [comment]
As far as I know, this bundle should work in Symfony3. If it does not, please open separate issue that describes exact problem so that we can fix it one by one. However, this bundle _should remain compatible with symfony2_, because I think there are still some production systems using it.

**Comment by Nercury** [comment]
Oh wait I don't have the permission to close the issue. Looks like permissions to my own bundle was removed when I left the company :D.

Ping @dariuszz123

**Comment by Nercury** [comment]
🎉

**Comment by Quix0r** [comment]
I then would recommend following (common across many projects)
- create now a branch from symphony2-compatible code and name it, e.g. `legacy/symphony2-compatible`
- continue on `master` or `develop` branch with symphony3 ports, regardless of being incompatible with symphony2 (which is old anyway, yes, encourage people to upgrade faster)
- state a **warning** notice in your `README.md` that the next changes will be incompatible with S2 and only S3+ from now on is supported in latest development branch and that there is a legacy branch (see above) for old and outdated S2

This way, you can keep S2 support partly alive and continue with S3 developments. Remember, that S3 may become outdated one day, too (same with PHP 5.6, 7.0, 7.1 ...).
